### ISSUE TITLE
柯大的「邪宋」可供參考

### ISSUE THREAD

**Issue by Hulenkius** [Honoka55/erjian-convert#1]

**Comment by Honoka55** [comment]
本以为是词库可以参考，去看了一下，只有字体制作方面可以参考。

邪宋没有二简向一简回转的功能，这部分的词库是最复杂、最不易整理的。一繁对多简也不能正确处理（“射雕英雄传中郭靖的雕像”两个“雕”二简不同，邪宋都是一样的）。

本项目的字体还很不完善但已有雏形，可能考虑继续沿用当前的处理方法（草案、修订草案分为两个字体文件，草案一表用unicode-range调用）。也可以考虑邪宋，不过没办法直接用，肯定要改造一下🤔
